language: java

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

install:
    - export main_repo_branch=$TRAVIS_BRANCH
    - echo $main_repo_branch
    - python getNeuroML.py $main_repo_branch  # will call mvn install on this & other repos
    
script:
    - mkdir results 
    
    # Test validate
    - ./jnml -validate ../NeuroML2/examples/NML2_FullNeuroML.nml
    
    # Print version info
    - ./jnml -h

